filebeat.inputs:
- type: filestream
  id: access-logs
  paths:
    - "/var/log/apache2/*.log"

output.kafka:
  hosts: ["kafka-cntr:9092"] # Corrected host and port
  topic: "logs" # Default topic
  topics:
    - topic: "error"
      when.contains:
        message: "ERR"
    - topic: "access"
      when.contains:
        message: "\"GET .*\" 200" # Improved regex
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000